version: 0.0
os: linux
files:
  - source: MessageAPI.war
    destination: /opt/tomcat/webapps/
  - source: FileReader.jar
    destination: /opt/pipeline/
  - source: DataReader.jar
    destination: /opt/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: cleanup.sh
      timeout: 300
      runas: root
